### ISSUE TITLE
"Problem requesting permission: Bluetooth Connect"

### ISSUE THREAD

**Issue by jtn20** [danielgjackson/noisecancel#4]
I recently installed this app (version 1.4) from F-Droid (thanks for helping get it on there!) on my Fairphone 2 running Android 9 (branded as "Fairphone Open OS" -- essentially AOSP, I think -- in particular it has no Google Mobile Services).

Unfortunately, I can't get this app to see my Bose NC 700 headphones. It seems unable to access Bluetooth at all. It seems to be some sort of permissions issue: when I tap on the gear-wheel "choose device" icon, it pops up a toast "Problem requesting permission: Bluetooth Connect".

I have never received any permission prompts from this app. If I go into the system's "App info", it says "Permissions: No permissions requested".

I have another app installed ([BLExplorer](https://f-droid.org/en/packages/org.ligi.blexplorer/)) which is able to use Bluetooth (and can see the Bose headphones). (This app's "App info" also says "Permissions: No permissions requested", so I guess that isn't significant. I don't recall if I originally got permission prompts from this app.)

(I'm not an Android developer, but I noticed a test for `Build.VERSION_CODES.S` in `MainActivity.kt`. I think that's Android 12, which is newer than my device. Is it possible that this app hasn't been tested on old Android versions like mine?)

**Comment by danielgjackson** [comment]
Ok, I think this is fixed in the [latest release 1.5](https://github.com/danielgjackson/noisecancel/releases) -- please try that APK directly if possible.  (Otherwise, I believe F-Droid should eventually auto-update off the repo tag.)

**Comment by jtn20** [comment]
I confirm it's all fixed for me, thanks!

(Sorry for slow reply -- didn't get around to trying your APK before 1.5 appeared on F-Droid, which it now has; that is the build I tested.)

**Comment by danielgjackson** [comment]
Great! Thanks for letting me know. 

I'm also happy F-Droid automatically updated/rebuilt the app from this repo's release tags - pretty handy!
